package com.speedy.skytrain;

import java.util.List;

/*
 * This class holds tweet specific data generated by MatsTwitterMaster for display
 * All of this information must be displayed in accordance with twitter's display requirements.
 * 
 */
public class Tweet {
	
	private String name;
	private String screen_name;
	private String content;
	private String timeStamp;
	private List<Hashtag> tags;
	private long id;
	
	Tweet(String auth,String screen, String text, String time, List<Hashtag> tags, long id){
		this.name = auth;
		this.screen_name = screen;
		this.content = text;
		this.timeStamp = time;
		this.tags = tags;
		this.id = id;
	}
	
	public String getName(){
		return this.name;
	}
	
	public String getScreenName(){
		return this.screen_name;
	}
	
	public String getText(){
		return this.content;
	}
	
	public String getTimeStamp(){
		return this.timeStamp;
	}
	
	public List<Hashtag> getTags(){
		return this.tags;
	}
	
	public long getId(){
		return this.id;
	}

}
